server:
  port: 8081

spring:
  application:
    name: Jpa-Relation

  datasource:
    password: Tiger2143@+%
    username: root
    url: jdbc:mysql://localhost:3306/jpa_db_all
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

